/** Design tokens from Stitch Vellum project (tailwind-config + designTheme) */
export const stitchColors = {
  'ink-black': '#141413',
  'on-primary-fixed-variant': '#474745',
  'tertiary-fixed-dim': '#cac5c5',
  'surface-dim': '#ddd9d8',
  'tertiary-fixed': '#e6e1e1',
  'secondary-fixed': '#ffdbd0',
  'primary-fixed-dim': '#c9c6c4',
  'inverse-primary': '#c9c6c4',
  'surface-container': '#f1edec',
  'on-primary-container': '#858382',
  'outline-variant': '#c7c7c0',
  'on-error': '#ffffff',
  'inverse-surface': '#313030',
  stone: '#9c9a92',
  'primary-fixed': '#e5e2e0',
  surface: '#fdf8f7',
  primary: '#000000',
  'primary-container': '#1c1c1a',
  'on-tertiary-fixed': '#1c1b1b',
  'terra-cotta': '#d97757',
  'inverse-on-surface': '#f4f0ef',
  'on-secondary-container': '#762c12',
  'vellum-white': '#faf9f5',
  outline: '#767872',
  'surface-container-low': '#f7f3f2',
  parchment: '#dedcd1',
  onyx: '#1f1e1d',
  'pale-azure': '#ccdbe8',
  'surface-tint': '#5f5e5d',
  'on-secondary': '#ffffff',
  'error-container': '#ffdad6',
  background: '#fdf8f7',
  'surface-container-lowest': '#ffffff',
  'surface-container-highest': '#e5e2e1',
  secondary: '#99462a',
  'surface-container-high': '#ebe7e6',
  'on-primary-fixed': '#1c1c1a',
  tertiary: '#000000',
  'on-primary': '#ffffff',
  'secondary-container': '#fe9572',
  'dusty-gray': '#73726c',
  graphite: '#3d3d3a',
  'surface-bright': '#fdf8f7',
  'on-tertiary-fixed-variant': '#484646',
  'on-background': '#1c1b1b',
  'on-secondary-fixed': '#390b00',
  'secondary-fixed-dim': '#ffb59e',
  'on-secondary-fixed-variant': '#7a2f15',
  'on-error-container': '#93000a',
  'snow-white': '#ffffff',
  'tertiary-container': '#1c1b1b',
  error: '#ba1a1a',
  'surface-variant': '#e5e2e1',
  'on-surface': '#1c1b1b',
  'on-tertiary': '#ffffff',
  'on-surface-variant': '#464742',
  'on-tertiary-container': '#868383',
} as const

export const stitchSpacing = {
  'gap-lg': '32px',
  'section-xl': '40px',
  'container-max': '1200px',
  'gap-md': '24px',
  unit: '8px',
  'gap-xs': '8px',
} as const

export const stitchFontSize = {
  h3: ['24px', { lineHeight: '1.33', fontWeight: '400' }],
  caption: ['12px', { lineHeight: '1.33', fontWeight: '400' }],
  h4: ['18px', { lineHeight: '1.33', fontWeight: '400' }],
  'label-caps': ['11px', { lineHeight: '1.33', letterSpacing: '0.05em', fontWeight: '500' }],
  'body-md': ['15px', { lineHeight: '1.4', fontWeight: '400' }],
  'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
  display: ['56px', { lineHeight: '1.2', fontWeight: '330' }],
  'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
  h2: ['30px', { lineHeight: '1.33', fontWeight: '400' }],
} as const

export const stitchFontFamily = {
  h3: ['var(--font-stitch-lora)', 'Lora', 'serif'],
  caption: ['var(--font-stitch-inter)', 'Inter', 'sans-serif'],
  h4: ['var(--font-stitch-lora)', 'Lora', 'serif'],
  'label-caps': ['var(--font-stitch-inter)', 'Inter', 'sans-serif'],
  'body-md': ['var(--font-stitch-inter)', 'Inter', 'sans-serif'],
  'body-sm': ['var(--font-stitch-inter)', 'Inter', 'sans-serif'],
  display: ['var(--font-stitch-lora)', 'Lora', 'serif'],
  'body-lg': ['var(--font-stitch-inter)', 'Inter', 'sans-serif'],
  h2: ['var(--font-stitch-lora)', 'Lora', 'serif'],
} as const
